version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building the React application...
      - echo "Building with environment variables:"
      - echo "REACT_APP_S3_BUCKET_NAME=$REACT_APP_S3_BUCKET_NAME"
      - echo "REACT_APP_AWS_REGION=$REACT_APP_AWS_REGION"
      - |
        # Create .env file with environment variables to ensure they're included in the build
        cat > .env << EOL
        REACT_APP_S3_BUCKET_NAME=${REACT_APP_S3_BUCKET_NAME}
        REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION}
        EOL
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
cache:
  paths:
    - 'frontend/node_modules/**/*'
