version: 0.2
phases:
  build:
    commands:
      - echo Deploying hosting resources...
      - aws cloudformation deploy --template-file infrastructure/resources/hosting-resources.yaml --stack-name ${STACK_NAME}-hosting-resources --parameter-overrides StackName=${STACK_NAME} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
  post_build:
    commands:
      - echo Hosting resources deployed
artifacts:
  files:
    - '**/*'
