AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage resources for Game Collection App'

Parameters:
  AppName:
    Type: String
    Default: 'game-collection'
    Description: 'Application name used for naming resources'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'prod'
    Description: 'Environment (dev or prod)'

Resources:
  # S3 Bucket for Thumbnails
  ThumbnailsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-thumbnails'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
  
  # S3 Bucket for Static Web Hosting
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-website'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  
  # S3 Bucket Policy for Website Bucket (CloudFront Access)
  WebsiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/*'
  
  # DynamoDB Table for Games
  GamesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AppName}-${Environment}-games'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
        - AttributeName: platform
          AttributeType: S
        - AttributeName: genre
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: gameId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: PlatformIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: platform
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GenreIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: genre
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false

Outputs:
  ThumbnailsBucketName:
    Description: 'Name of the S3 bucket for thumbnails'
    Value: !Ref ThumbnailsBucket
    Export:
      Name: !Sub '${AppName}-${Environment}-ThumbnailsBucketName'
  
  ThumbnailsBucketArn:
    Description: 'ARN of the S3 bucket for thumbnails'
    Value: !GetAtt ThumbnailsBucket.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-ThumbnailsBucketArn'
  
  WebsiteBucketName:
    Description: 'Name of the S3 bucket for website hosting'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteBucketName'
  
  WebsiteBucketArn:
    Description: 'ARN of the S3 bucket for website hosting'
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteBucketArn'
  
  WebsiteURL:
    Description: 'URL of the website'
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteURL'
  
  GamesTableName:
    Description: 'Name of the DynamoDB table for games'
    Value: !Ref GamesTable
    Export:
      Name: !Sub '${AppName}-${Environment}-GamesTableName'
  
  GamesTableArn:
    Description: 'ARN of the DynamoDB table for games'
    Value: !GetAtt GamesTable.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-GamesTableArn'
