AWSTemplateFormatVersion: '2010-09-09'
Description: 'Frontend resources for Game Collection App'

Parameters:
  AppName:
    Type: String
    Default: 'game-collection'
    Description: 'Application name used for naming resources'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'prod'
    Description: 'Environment (dev or prod)'

Resources:
  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: 'AWS::CloudFront::OriginAccessControl'
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AppName}-${Environment}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: !Sub '${AppName}-${Environment} CloudFront Distribution'
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations to reduce cost
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com'
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Update S3 Bucket Policy for CloudFront
  WebsiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: 
        Fn::ImportValue: !Sub '${AppName}-${Environment}-WebsiteBucketName'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: 
              !Join 
                - ''
                - - Fn::ImportValue: !Sub '${AppName}-${Environment}-WebsiteBucketArn'
                  - '/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

Outputs:
  CloudFrontDistributionId:
    Description: 'ID of the CloudFront Distribution'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AppName}-${Environment}-CloudFrontDistributionId'
  
  CloudFrontDomainName:
    Description: 'Domain name of the CloudFront Distribution'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AppName}-${Environment}-CloudFrontDomainName'
  
  WebsiteURL:
    Description: 'URL of the website'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteURL'
