AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild Projects for Game Collection App CI/CD'

Parameters:
  AppName:
    Type: String
    Description: 'Application name used for naming resources'
  
  Environment:
    Type: String
    Description: 'Environment (dev or prod)'
  
  CodeBuildServiceRoleArn:
    Type: String
    Description: 'ARN of the CodeBuild service role'

Resources:
  # CodeBuild Project for Frontend Build
  FrontendBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AppName}-${Environment}-frontend-build'
      Description: 'Build frontend for Game Collection App'
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: false
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 16
              commands:
                - cd frontend
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            base-directory: frontend/build
            files:
              - '**/*'
      TimeoutInMinutes: 15

Outputs:
  FrontendBuildProjectName:
    Description: 'Name of the frontend build CodeBuild project'
    Value: !Ref FrontendBuildProject
    Export:
      Name: !Sub '${AppName}-${Environment}-FrontendBuildProjectName'
  
  FrontendBuildProjectArn:
    Description: 'ARN of the frontend build CodeBuild project'
    Value: !GetAtt FrontendBuildProject.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-FrontendBuildProjectArn'
