AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Buckets for Game Collection App CI/CD'

Parameters:
  AppName:
    Type: String
    Description: 'Application name used for naming resources'
  
  Environment:
    Type: String
    Description: 'Environment (dev or prod)'

Resources:
  # CodePipeline Artifacts Bucket
  ArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-pipeline-artifacts'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket for Static Web Hosting
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-website'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  ArtifactsBucketName:
    Description: 'Name of the S3 bucket for pipeline artifacts'
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${AppName}-${Environment}-ArtifactsBucketName'
  
  ArtifactsBucketArn:
    Description: 'ARN of the S3 bucket for pipeline artifacts'
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-ArtifactsBucketArn'
  
  WebsiteBucketName:
    Description: 'Name of the S3 bucket for website hosting'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteBucketName'
  
  WebsiteBucketArn:
    Description: 'ARN of the S3 bucket for website hosting'
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AppName}-${Environment}-WebsiteBucketArn'
