AWSTemplateFormatVersion: '2010-09-09'
Description: 'Prerequisites for the S3 Photo Gallery CI/CD Pipeline'

Resources:
  # S3 bucket for CodePipeline artifacts
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 's3-photo-gallery-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # IAM role for CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonCloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess

  # IAM role for CloudFormation
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /service-role/

  # IAM role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildBasePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*:*'
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject

Outputs:
  ArtifactBucketName:
    Description: Name of the S3 bucket for CodePipeline artifacts
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactBucketName'

  CodePipelineServiceRoleArn:
    Description: ARN of the IAM role for CodePipeline
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineServiceRoleArn'

  CloudFormationServiceRoleArn:
    Description: ARN of the IAM role for CloudFormation
    Value: !GetAtt CloudFormationServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudFormationServiceRoleArn'

  CodeBuildServiceRoleArn:
    Description: ARN of the IAM role for CodeBuild
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CodeBuildServiceRoleArn'
