AWSTemplateFormatVersion: '2010-09-09'
Description: 'Meta Pipeline for S3 Photo Gallery - Updates Main Pipeline Automatically'

Parameters:
  GitHubOwner:
    Type: String
    Default: Tatsuki-Yamada
    Description: GitHub repository owner
  
  GitHubRepo:
    Type: String
    Default: claude-test
    Description: GitHub repository name
  
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub repository branch
  
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub OAuth token
  
  MainStackName:
    Type: String
    Default: s3-photo-gallery
    Description: Name of the main pipeline stack
  
  PrerequisitesStackName:
    Type: String
    Default: s3-photo-gallery-prerequisites
    Description: Name of the prerequisite resources CloudFormation stack

Resources:
  # メインパイプラインを実行するためのCodeBuildプロジェクト - シンプルなアプローチ
  TriggerMainPipelineProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${MainStackName}-trigger-main-pipeline'
      Description: 'Trigger the main pipeline after meta-pipeline updates it'
      ServiceRole: 
        Fn::ImportValue: !Sub '${PrerequisitesStackName}-CodeBuildServiceRoleArn'
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: MAIN_PIPELINE_NAME
            Value: !Sub '${MainStackName}-pipeline'
            Type: PLAINTEXT
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Triggering main pipeline: $MAIN_PIPELINE_NAME"
                - aws codepipeline start-pipeline-execution --name $MAIN_PIPELINE_NAME || echo "Failed to trigger pipeline, but continuing anyway"
          artifacts:
            files:
              - README.md
      TimeoutInMinutes: 5

  # CloudWatch event to detect changes in the infrastructure/pipeline directory
  PipelineChangeDetector:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${MainStackName}-pipeline-change-detector'
      Description: 'Detect changes in the pipeline directory and trigger the meta-pipeline'
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${GitHubRepo}'
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref GitHubBranch
      State: ENABLED
      Targets:
        - Arn: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${MetaPipeline}'
          Id: TriggerMetaPipeline
          RoleArn: 
            Fn::ImportValue: !Sub '${PrerequisitesStackName}-CloudWatchEventsServiceRoleArn'

  MetaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${MainStackName}-meta-pipeline'
      RoleArn: 
        Fn::ImportValue: !Sub '${PrerequisitesStackName}-CodePipelineServiceRoleArn'
      ArtifactStore:
        Type: S3
        Location: 
          Fn::ImportValue: !Sub '${PrerequisitesStackName}-ArtifactBucketName'
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceCode
        
        - Name: UpdatePipeline
          Actions:
            - Name: UpdateMainPipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: 
                  Fn::ImportValue: !Sub '${PrerequisitesStackName}-CloudFormationServiceRoleArn'
                StackName: !Ref MainStackName
                TemplatePath: SourceCode::infrastructure/pipeline/main-pipeline.yaml
                Capabilities: CAPABILITY_NAMED_IAM
                ParameterOverrides: !Sub |
                  {
                    "GitHubOwner": "${GitHubOwner}",
                    "GitHubRepo": "${GitHubRepo}",
                    "GitHubBranch": "${GitHubBranch}",
                    "GitHubToken": "${GitHubToken}",
                    "PrerequisitesStackName": "${PrerequisitesStackName}"
                  }
              InputArtifacts:
                - Name: SourceCode
        
        # メインパイプラインを直接実行するステージ
        - Name: TriggerMainPipeline
          Actions:
            - Name: TriggerMainPipeline
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref TriggerMainPipelineProject
              InputArtifacts:
                - Name: SourceCode

Outputs:
  MetaPipelineUrl:
    Description: URL to the Meta Pipeline console
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${MetaPipeline}
  
  AutomationDetails:
    Description: Automation workflow details
    Value: "When the meta-pipeline completes, it will automatically trigger the main pipeline."
